title:              It's Not You, It's America
email:              mleovrgl
description:        "Help validate people's struggles by shining light on the real problem: America/Society"
author:             Zak Abdisalan
baseurl:            "/blog"
url:                "https://ZaksCode.github.io"

# Social Profiles
twitter_username:
github_username:    ZaksCode
facebook_username:
instagram_username:
linkedin_username:  sakaviye-abdisalan-b14362110

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
